version: '3.5'

services:
  backend:
      image: jupaste/backend
      environment: 
        - DB_PASSWORD= "example"
        - DB_NAME= "testdb"
        - DB_HOST=db
        - DB_USERNAME=postgres
      ports: 
        - "8000:8000"
  frontend:
      image: jupaste/frontend
      ports: 
        - "5000:5000"
  db:
       image: postgres
       environment:
        - POSTGRES_PASSWORD= "example"
        - POSTGRES_DB= "testdb"
