version: '3.5'

services:
  backend:
      image: jupaste/backend
      environment: 
        - REDIS="localhost:6379"
        - REDIS=redis
      ports: 
        - "8000:8000"
  frontend:
      image: jupaste/frontend
      ports: 
        - "5000:5000"
  redis:
      image: redis
      ports:
        - "6379:6379"
