version: '3.5'

services:
    redis:
        image: redis
        ports:
            - "6379:6379"    
    backend:
        image: jupaste/backend
        environment:
            - REDIS=redis
            - REDIS_PORT=6379
            - DB_PASSWORD= "example"
            - DB_NAME= "testdb"
            - DB_HOST=db
            - DB_USERNAME=postgres
        ports: 
            - "8000:8000"
    frontend:
        image: jupaste/frontend
        ports: 
            - "5000:5000"
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD= "example"
            - POSTGRES_DB= "testdb"
    nginx:
        image: nginx
        ports:
            - "80:80"
        depends_on:
            - frontend
            - backend
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
    config:

